
# Microservice application name.
spring.application.name: challenge-products-service
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:local}
spring.cloud.config.enabled: false

server.context-path: ${CONTEXT_PATH:/}
server.port: 8082

